# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Install dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev

# Set working directory
WORKDIR /app

# Copy source code
COPY . /app

# Install python dependencies (use pip instead of pipenv/poetry for simplicity)
RUN pip install --no-cache-dir -r <(grep -v "^#" pyproject.toml | grep -E '^[^\[]') || true

# Instead, manually install dependencies
RUN pip install --no-cache-dir httpx mcp[cli]>=1.6.0

# Expose port if needed (not necessary for stdio transport)

# Command
CMD ["python3", "server.py"]